# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HqFsCs7tSxy34vLjTIP6mQJuUyUvZ9mS
"""

from fastapi import FastAPI
import os
import uvicorn

app = FastAPI(title="Test FastAPI")

@app.get("/")
def home():
    return {"message": "Hello, Render!"}

# Run app if executed directly
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)